# Generated by Django 4.1.5 on 2023-01-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('rasm', models.ImageField(blank=True, upload_to='')),
                ('daraja', models.CharField(choices=[('Boshlangich', 'Boshlangich'), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori')], max_length=15)),
                ('narx', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('sana', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('malumot', models.TextField()),
                ('rasm', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(default='Yangi', max_length=15)),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kurs')),
                ('profil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz_kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kurs')),
                ('ustoz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ustoz')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kurs')),
                ('profil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.SmallIntegerField(default=5)),
                ('matn', models.TextField()),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kurs')),
                ('profil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profil')),
            ],
        ),
    ]
