# Generated by Django 4.1.5 on 2023-01-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='izoh',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xarid',
            name='sana',
            field=models.DateField(blank=True, null=True),
        ),
    ]
